name: Maven Build
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
 
      - name: Show project structure (debug)
        run: ls -R sample/
 
      - name: Build with Maven
        run: mvn clean install
        working-directory: sample/
 
      - name: Show JAR file (debug)
        run: ls -l sample/target/*.jar
 
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-jar
          path: sample/target/*.jar
 
