name: DEMO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '11'

    - name: List root contents
      run: ls -R
    
    - name: Build with Maven
      run: mvn clean install
      working-directory: sample/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: maven-jar
        path: sample/target/*.jar

